main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path("create-order/", views.create_order_view, name="create_order"),
    path(
        "<int:pk>/create-checkout-session/",
        views.create_checkout_session,
        name="create-checkout-session"
    ),
    path("success/", views.success_view, name="success"),
    path("cancel/", views.cancel_view, name="cancel"),
]

store_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("subscribe/", include("subscribe.urls", namespace="subscribe")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "store_service.views.custom_404"
handler500 = "store_service.views.custom_500"

orders/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from goods.models import Product

from users.models import User


class OrderItemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    NEW = "New"
    INPROCESSING = "In processing"
    SHIPPED = "Shipped"
    RECEIVED = "Received"

    PENDING = "Pending"
    PAID = "Paid"
    CANCELLED = "Cancelled"

    STATUS_PAYMENT = [
        (PENDING, "Pending"),
        (PAID, "Paid"),
        (CANCELLED, "Cancelled"),
    ]

    STATUS_ORDER = (
        (NEW, "New"),
        (INPROCESSING, "In processing"),
        (SHIPPED, "Shipped"),
        (RECEIVED, "Received"),
    )

    user = models.ForeignKey(
        to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None
    )
    email = models.EmailField(blank=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    shipping_address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    zipcode = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    requires_delivery = models.BooleanField(default=False)
    payment_on_get = models.BooleanField(default=False)
    status_order = models.CharField(max_length=20, choices=STATUS_ORDER, default=NEW)
    is_paid = models.BooleanField(default=False)
    paid_amount = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    status_payment = models.CharField(
        max_length=10, choices=STATUS_PAYMENT, default=PENDING
    )
    session_url = models.URLField(max_length=500, blank=True)
    session_id = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"Order № {self.pk} | Consumer {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, related_name="order_items")
    product = models.ForeignKey(
        to=Product, on_delete=models.SET_DEFAULT, null=True, related_name="order_items", default=None
    )
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = OrderItemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f'Product "{self.name}" | Order № {self.order.pk}'

orders/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField


class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    phone_number = PhoneNumberField(required=False)
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
        ],
    )
    shipping_address = forms.CharField(required=False)
    city = forms.CharField(required=False)
    country = forms.CharField(required=False)
    zipcode = forms.IntegerField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", 'False'),
            ("1", 'True'),
        ],
    )

orders/views.py
import logging
import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError

from django.db import transaction
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods

from carts.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem

logger = logging.getLogger(__name__)


BASE_URL = settings.BASE_URL
stripe.api_key = settings.STRIPE_SECRET_KEY


@login_required
def create_order_view(request):
    if request.method == "POST":
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        order = Order.objects.create(
                            user=user,
                            email=form.cleaned_data["email"],
                            phone_number=form.cleaned_data["phone_number"],
                            requires_delivery=form.cleaned_data["requires_delivery"],
                            shipping_address=form.cleaned_data["shipping_address"],
                            city=form.cleaned_data["city"],
                            country=form.cleaned_data["country"],
                            zipcode=form.cleaned_data["zipcode"],
                            payment_on_get=form.cleaned_data["payment_on_get"],
                        )

                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.product.sell_price()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                logger.error(
                                    f"Insufficient quantity of goods {name} in stock. Available - {product.quantity}"
                                )
                                raise ValidationError(
                                    f"Insufficient quantity of goods {name} in stock. Available - {product.quantity}"
                                )

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        cart_items.delete()

                        logger.info("Your order has been placed successfully!")
                        messages.success(request, "Your order has been placed successfully!")
                        return redirect("users:profile")
            except ValidationError as e:
                logger.error(f"Error: {str(e)}")
                messages.warning(request, str(e))
                return redirect("cart:order")
        else:
            logger.error("Please correct the errors in the order form.")
            messages.warning(request, "Please correct the errors in the form.")
    else:
        initial = {
            "first_name": request.user.first_name,
            "last_name": request.user.last_name,
            "email": request.user.email,
        }

        form = CreateOrderForm(initial=initial)

    context = {
        "title": "House Style - Making of Order",
        "form": form,
        "orders": True,
    }
    return render(request=request, template_name="orders/create_order.html", context=context)


@require_http_methods(["GET"])
def create_checkout_session(request, *args, **kwargs):
    order_id = kwargs["pk"]
    order = Order.objects.get(id=order_id)

    checkout_session = stripe.checkout.Session.create(
        payment_method_types=["card"],
        line_items=[
            {
                "price_data": {
                    "currency": "usd",
                    "unit_amount": int(order.order_items.total_price() * 100),
                    "product_data": {
                        "name": f"Order №{order.id}",
                        "description": "Payment of the order",
                    },
                },
                "quantity": 1,
            },
        ],
        metadata={
            "order_id": order.id
        },
        mode="payment",
        success_url=BASE_URL + "/orders/success/",
        cancel_url=BASE_URL + "/orders/cancel/",
    )

    order.session_id = checkout_session.id
    order.session_url = checkout_session.url
    order.save()

    return redirect(order.session_url)


def success_view(request):
    orders = Order.objects.all()
    for order in orders:
        if order.session_id:
            order.status_payment = Order.PAID
            order.is_paid = True
            order.status_order = Order.SHIPPED
            order.paid_amount = order.order_items.total_price()

            order.save()

    context = {
        "title": "House Style - Payment Success"
    }

    return render(request, "orders/success.html", context=context)


def cancel_view(request):
    orders = Order.objects.all()

    for order in orders:
        if order.session_id and order.is_paid is False:
            order.status_payment = Order.CANCELLED

            order.save()

    context = {
        "title": "House Style - Payment Cancelled"
    }

    return render(request, "orders/cancel.html", context=context)

orders/templates/orders/cancel.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
          <h2 class="text-center mb-4">Payment canceled</h2>

          <section>
            <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
          </section>

        </div>
      </div>
    </div>
  </div>

{% endblock %}

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

  <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
      <h3 class="text-center mb-4">Selected items</h3>
      <div class="container" id="cart-items-container">
        <!-- Cart marking -->
        {% user_carts request as carts %}

        {% include "carts/includes/included_cart.html" %}
        <!-- End cart marking -->
      </div>
    </div>
    <!-- Order detail -->
    <div class="container">
      <h3 class="text-center">Order detail</h3>
      <div class="card mb-3">
        <div class="card-body">

          <form action="{% url "orders:create_order" %}" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="id_first_name" class="form-label">First Name*:</label>
                <input type="text" class="form-control" id="id_first_name"
                       value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                       name="first_name" required>
                 {% if form.first_name.errors %}
                   <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                 {% endif %}
              </div>
              <div class="col-md-6 mb-3">
                <label for="id_last_name" class="form-label">Last Name*:</label>
                <input type="text" class="form-control" id="id_last_name" name="last_name"
                       value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" required>
                {% if form.last_name.errors %}
                  <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                {% endif %}
              </div>
              <div class="col-md-6 mb-3">
                <label for="id_email" class="form-label">Email Address*:</label>
                <input type="email" class="form-control" id="id_email" name="email"
                       value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required>
                {% if form.email.errors %}
                  <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                {% endif %}
              </div>
              <div class="col-md-6 mb-3">
                <label for="id_phone_number" class="form-label">Phone number*:</label>
                <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                       value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                       placeholder="In formate: XXX-XXX-XX-XX">
                {% if form.phone_number.errors %}
                  <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
                {% endif %}
              </div>
              <div class="col-md-12 mb-3">
                <label for="delivery" class="form-label">Delivery option: </label>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="requires_delivery"
                         id="id_requires_delivery" value="1" checked>
                  <label class="form-check-label" for="id_requires_delivery">Need delivery</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="requires_delivery"
                         id="id_requires_delivery" value="0">
                  <label class="form-check-label" for="id_requires_delivery">Self-delivery</label>
                </div>
              </div>

              <div class="mb-3" id="deliveryAddressField">
                <div class="row">
                  <div class="col-md-6 mb-3">
                    <label for="id_shipping_address" class="form-label">Shipping address*:</label>
                    <input type="text" class="form-control" id="id_shipping_address" name="shipping_address"
                         value="{% if form.shipping_address.value %}{{ form.shipping_address.value }}{% endif %}">
                    {% if form.shipping_address.errors %}
                      <div class="alert alert-danger alert-dismissible fade show">{{form.shipping_address.errors}}</div>
                    {% endif %}
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="id_city" class="form-label">City*:</label>
                    <input type="text" class="form-control" id="id_city" name="city"
                         value="{% if form.city.value %}{{ form.city.value }}{% endif %}">
                    {% if form.city.errors %}
                      <div class="alert alert-danger alert-dismissible fade show">{{form.city.errors}}</div>
                    {% endif %}
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="id_country" class="form-label">Country*:</label>
                    <input type="text" class="form-control" id="id_country" name="country"
                         value="{% if form.country.value %}{{ form.country.value }}{% endif %}">
                    {% if form.country.errors %}
                      <div class="alert alert-danger alert-dismissible fade show">{{form.country.errors}}</div>
                    {% endif %}
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="id_zipcode" class="form-label">Zipcode*:</label>
                    <input type="number" class="form-control" id="id_zipcode" name="zipcode"
                         value="{% if form.zipcode.value %}{{ form.zipcode.value }}{% endif %}">
                    {% if form.zipcode.errors %}
                      <div class="alert alert-danger alert-dismissible fade show">{{form.zipcode.errors}}</div>
                    {% endif %}
                  </div>
                </div>
              </div>

              <div class="col-md-12 mb-3">
                <label class="form-label">Payment option: </label>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="payment_on_get"
                         id="id_payment_on_get" value="0" checked>
                  <label class="form-check-label" for="id_payment_on_get">Payment by card</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="payment_on_get"
                         id="id_payment_on_get" value="1">
                  <label class="form-check-label" for="id_payment_on_get">Cash/card on receipt</label>
                  {% if form.payment_on_get.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">{{form.payment_on_get.errors}}</div>
                  {% endif %}
                </div>
              </div>

            </div>
            <button type="submit" class="btn btn-dark">Place order</button>
          </form>

        </div>
      </div>
    </div>
  </div>

{% endblock %}

orders/templates/orders/success.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
          <h2 class="text-center mb-4">Thanks for your order!</h2>

          <section>
            <p>
              We appreciate your business! If you have any questions, please email
              <a href="#">orders@example.com</a>.
            </p>
          </section>

        </div>
      </div>
    </div>
  </div>

{% endblock %}