goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"

urlpatterns = [
    path("search/", views.catalog_view, name="search"),
    path("favorite-products/", views.favorite_products_view, name="favorite_products"),
    path("toggle-favorite/", views.toggle_favorite_view, name="toggle_favorite"),
    path("add-rating/<int:product_id>/", views.add_rating_view, name="add_rating"),
    path("create-category/", views.category_create_view, name="create_category"),
    path("create-product/", views.product_create_view, name="create_product"),
    path("<slug:category_slug>/", views.catalog_view, name="index"),
    path("product/<slug:product_slug>/", views.product_view, name="product"),
    path("product/<slug:product_slug>/edit/", views.product_update_view, name="product_update"),
    path("product/<slug:product_slug>/remove/", views.product_delete_view, name="product_delete"),
    path("review/<int:product_id>/", views.create_review, name="review-create"),
]

main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

store_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("subscribe/", include("subscribe.urls", namespace="subscribe")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "store_service.views.custom_404"
handler500 = "store_service.views.custom_500"

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("profile/", views.profile_view, name="profile"),
    path("users-cart/", views.users_cart_view, name="users_cart"),
    path("logout/", views.logout_view, name="logout"),
    path("<int:pk>/password/", views.change_password_view, name="password-change"),
    path("password-success/", views.password_success_view, name="password-success"),
    path(
        "reset_password/", views.reset_password_view, name="reset_password"
    ),
    path(
        "reset_password_sent/", views.reset_password_done_view, name="password_reset_done"
    ),
    path(
        "reset/<uidb64>/<token>/", views.reset_password_confirm_view, name="password_reset_confirm"
    ),
    path(
        "reset_password_complete/", views.reset_password_complete_view, name="password_reset_complete"
    ),
]

goods/models.py
import os
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


def product_image_file_path(instance, filename):
    _, extension = os.path.splitext(filename)
    filename = f"{slugify(instance.name)}-{uuid.uuid4()}{extension}"

    return os.path.join("uploads/products/", filename)


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    class Meta:
        ordering = ("id",)
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        index_together = (("id", "slug"),)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True)
    image_product = models.ImageField(
        upload_to=product_image_file_path, blank=True, null=True
    )
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discount = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    quantity = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(
        to=Category, on_delete=models.CASCADE, related_name="products"
    )

    class Meta:
        ordering = ("id",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})

    def display_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)

        return self.price

    def get_review(self):
        return self.product_review.filter(parent__isnull=True)

    def average_rating(self):
        ratings = self.product_rating.all()
        if ratings:
            return sum([rating.rating for rating in ratings]) / len(ratings)
        else:
            return 0


class Review(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_review"
    )
    text = models.TextField(blank=True)
    parent = models.ForeignKey(
        "self", on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Parent"
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_review"
    )

    def __str__(self):
        return f"{self.user} - {self.product}"


class FavoriteProduct(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("user", "product")


class Rating(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_rating"
    )
    rating = models.PositiveIntegerField()
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_rating"
    )

    def __str__(self):
        return f"{self.rating} - {self.product}"

templates/includes/cart_button.html
{% load static %}

{% load carts_tags %}

{% user_carts request as carts %}

<div>
  <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
          aria-expanded="false">
    <img class="mx-1" src="{% static 'deps/icons/basket2-fill.svg' %}" alt="Catalog Icon" width="24"
         height="24">
    <span id="goods-in-cart-count">{{ carts.total_quantity }}</span>
  </button>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal"
                aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h3 class="text-center mb-4">Cart</h3>
        <div class="container" id="cart-items-container">

          <!-- Start cart content -->
          {% include "carts/includes/included_cart.html" %}
          <!-- End cart content -->
        </div>

      </div>
    </div>
  </div>
</div>

templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark fixed-top" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            Information
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item  text-white" href="#">Delivery and payment</a></li>
            <li><a class="dropdown-item  text-white" href="#">Contacts</a></li>
            <li><a class="dropdown-item  text-white" href="#">About us</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link  text-white" href="{% url 'user:users_cart' %}">Cart</a>
        </li>
      </ul>

      <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success text-white" type="submit">Search</button>
      </form>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link  text-white" href="{% url 'user:login' %}">Sign in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link  text-white" href="{% url 'user:register' %}">Register</a>
          </li>
        {% else %}

          <a id="fav-icon" class="nav-link" href="{% url 'catalog:favorite_products' %}">
            <i class="bi bi-heart-fill text-center"></i>
          </a>
          {% if request.user.favoriteproduct_set.count > 0 %}
            <p id="fav-count" class="favorites-count">{{ request.user.favoriteproduct_set.count }}</p>
          {% else %}
            <p id="fav-count" class="favorites-count">0</p>
          {% endif %}

          <li class="nav-item dropdown">

            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
               data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{% if user.image_user %}{{ user.image_user.url }}
                   {% else %}{% static 'deps/images/baseavatar.jpg' %}{% endif %}"
                   alt="User image" class="img-fluid rounded-circle" style="max-width: 20px;">&#8194;
              Hello, {{ user.username }}
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item  text-white" href="{% url 'user:users_cart' %}">Cart</a></li>
              <li><a class="dropdown-item  text-white" href="{% url 'user:profile' %}">Personal account</a>
              </li>
              {% if user.is_staff %}
                <li><a class="dropdown-item  text-white" href="{% url 'admin:index' %}">Admin panel</a></li>
                <li><a class="dropdown-item  text-white" href="{% url 'catalog:create_category' %}">Add category</a></li>
                <li><a class="dropdown-item  text-white" href="{% url 'catalog:create_product' %}">Add product</a></li>
              {% endif %}
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item  text-white" href="{% url 'user:logout' %}">Logout</a></li>
            </ul>
          </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>
<br><br><br>

templates/includes/notifications.html
{% load static %}

{% if form.non_field_errors %}
  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
          {{form.non_field_errors}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    </div>
  </div>
{% endif %}

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'success' %}
            <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
              {{ message }}
            </div>
          {% endif %}
          {% if message.tags == 'warning' %}
            <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      {% else %}
        <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
        </div>
      {% endif %}
    </div>
  </div>
</div>