carts/urls.py
from django.urls import path

from carts import views

app_name = "carts"

urlpatterns = [
    path("cart_add/", views.cart_add_view, name="cart_add"),
    path("cart_change/", views.cart_change_view, name="cart_change"),
    path("cart_remove/", views.cart_remove_view, name="cart_remove"),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"

urlpatterns = [
    path("search/", views.catalog_view, name="search"),
    path("favorite-products/", views.favorite_products_view, name="favorite_products"),
    path("toggle-favorite/", views.toggle_favorite_view, name="toggle_favorite"),
    path("add-rating/<int:product_id>/", views.add_rating_view, name="add_rating"),
    path("create-category/", views.category_create_view, name="create_category"),
    path("create-product/", views.product_create_view, name="create_product"),
    path("<slug:category_slug>/", views.catalog_view, name="index"),
    path("product/<slug:product_slug>/", views.product_view, name="product"),
    path("product/<slug:product_slug>/edit/", views.product_update_view, name="product_update"),
    path("product/<slug:product_slug>/remove/", views.product_delete_view, name="product_delete"),
    path("review/<int:product_id>/", views.create_review, name="review-create"),
]

main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

store_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("subscribe/", include("subscribe.urls", namespace="subscribe")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "store_service.views.custom_404"
handler500 = "store_service.views.custom_500"

goods/models.py
import os
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


def product_image_file_path(instance, filename):
    _, extension = os.path.splitext(filename)
    filename = f"{slugify(instance.name)}-{uuid.uuid4()}{extension}"

    return os.path.join("uploads/products/", filename)


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    class Meta:
        ordering = ("id",)
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        index_together = (("id", "slug"),)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True)
    image_product = models.ImageField(
        upload_to=product_image_file_path, blank=True, null=True
    )
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discount = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    quantity = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(
        to=Category, on_delete=models.CASCADE, related_name="products"
    )

    class Meta:
        ordering = ("id",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})

    def display_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)

        return self.price

    def get_review(self):
        return self.product_review.filter(parent__isnull=True)

    def average_rating(self):
        ratings = self.product_rating.all()
        if ratings:
            return sum([rating.rating for rating in ratings]) / len(ratings)
        else:
            return 0


class Review(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_review"
    )
    text = models.TextField(blank=True)
    parent = models.ForeignKey(
        "self", on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Parent"
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_review"
    )

    def __str__(self):
        return f"{self.user} - {self.product}"


class FavoriteProduct(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("user", "product")


class Rating(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_rating"
    )
    rating = models.PositiveIntegerField()
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_rating"
    )

    def __str__(self):
        return f"{self.rating} - {self.product}"

goods/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Value, BooleanField
from django.http import HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from goods.forms import CategoryForm, ProductForm, ReviewForm
from goods.models import Product, FavoriteProduct, Rating
from goods.utils import q_search

logger = logging.getLogger(__name__)


def catalog_view(request, category_slug: str = None):
    page = request.GET.get("page", 1)
    on_sale = request.GET.get("on_sale", None)
    order_by = request.GET.get("order_by", None)
    query = request.GET.get("q", None)

    goods = Product.objects.all()

    favorite_products = []
    if request.user.is_authenticated:
        favorite_products = (
            FavoriteProduct.objects.filter(user=request.user)
            .values_list("product_id", flat=True)
        )

    if category_slug and category_slug != "all-goods":
        goods = goods.filter(category__slug=category_slug)

    if query:
        goods = q_search(query)

    if on_sale:
        goods = goods.filter(discount__gt=0)

    if order_by and order_by != "default":
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, 3)
    current_page = paginator.page(int(page))

    context = {
        "title": "House Style - Catalog",
        "favorite_products": favorite_products,
        "goods": current_page,
        "slug_url": category_slug
    }

    return render(
        request=request, template_name="goods/catalog.html", context=context
    )


def product_view(request, product_slug: str):
    try:
        product = Product.objects.get(slug=product_slug)
    except Product.DoesNotExist:
        logger.error("Such Product not found. Error 404")
        raise Http404("Product not found")

    favorite_products = []
    if request.user.is_authenticated:
        favorite_products = (
            FavoriteProduct.objects.filter(user=request.user)
            .values_list("product_id", flat=True)
        )

    context = {
        "title": f"House Style - {product.name}",
        "product": product,
        "favorite_products": favorite_products,
    }

    return render(
        request=request, template_name="goods/product.html", context=context
    )


def is_admin(user):
    return user.is_authenticated and user.is_staff


@login_required
def category_create_view(request):
    if is_admin(request.user):
        if request.method == "POST":
            form = CategoryForm(data=request.POST)
            if form.is_valid():
                form.save()

                logger.info("Category successfully created")
                messages.success(request, "Category successfully created")
                return HttpResponseRedirect(reverse("main:index"))
        else:
            form = CategoryForm()

        context = {
            "title": "House Style - Create Category",
            "form": form
        }
        return render(
            request=request, template_name="goods/category_create.html", context=context
        )
    else:
        logger.warning("You do not have permission to create categories.")
        messages.warning(request, "You do not have permission to create categories.")
        return HttpResponseRedirect(reverse("main:index"))


@login_required
def product_create_view(request):
    if is_admin(request.user):
        if request.method == "POST":
            form = ProductForm(data=request.POST)
            if form.is_valid():
                form.save()

                logger.info("Product successfully created")
                messages.success(request, "Product successfully created")
                return HttpResponseRedirect(reverse("main:index"))
        else:
            form = ProductForm()

        context = {
            "title": "House Style - Create Product",
            "form": form
        }
        return render(
            request=request, template_name="goods/product_create.html", context=context
        )
    else:
        logger.warning("You do not have permission to create products.")
        messages.warning(request, "You do not have permission to create products.")
        return HttpResponseRedirect(reverse("main:index"))


@login_required
def product_update_view(request, product_slug: str):
    product = get_object_or_404(Product, slug=product_slug)

    if is_admin(request.user):
        if request.method == "POST":
            form = ProductForm(request.POST, instance=product)
            if form.is_valid():
                form.save()

                logger.info("Product successfully updated")
                messages.success(request, "Product successfully updated")
                return HttpResponseRedirect(product.get_absolute_url())
        else:
            form = ProductForm(instance=product)

        context = {
            "title": "House Style - Update Product",
            "form": form
        }
        return render(
            request=request, template_name="goods/product_update.html", context=context
        )
    else:
        logger.warning("You do not have permission to update products.")
        messages.warning(request, "You do not have permission to update products.")
        return HttpResponseRedirect(product.get_absolute_url())


@login_required
def product_delete_view(request, product_slug: str):
    product = get_object_or_404(Product, slug=product_slug)

    if is_admin(request.user):
        if request.method == "POST":
            product.delete()

            logger.info("Product successfully removed")
            messages.success(request, "Product successfully removed")
            return HttpResponseRedirect(reverse("main:index"))

        context = {
            "title": "House Style - Remove Product",
            "product": product,
        }
        return render(
            request=request, template_name="goods/product_confirm_delete.html", context=context
        )
    else:
        logger.warning("You do not have permission to remove products.")
        messages.warning(request, "You do not have permission to remove products.")
        return HttpResponseRedirect(product.get_absolute_url())


@login_required
@require_POST
def create_review(request, product_id: int):
    product = get_object_or_404(Product, id=product_id)

    data = request.POST.copy()
    data.update({"user": request.user.id})
    form = ReviewForm(data)

    if form.is_valid():
        review = form.save(commit=False)
        if request.POST.get("parent", None):
            review.parent_id = int(request.POST.get("parent"))
        review.user = request.user
        review.product = product
        review.save()

        logger.info("Review successfully added.")
        messages.success(request, "Review successfully added.")
    else:
        logger.warning("Failed to add the review. Please check the form.")
        messages.warning(request, "Failed to add the review. Please check the form.")

    return redirect(product.get_absolute_url())


@login_required
def favorite_products_view(request):
    user = request.user
    favorite_products = (
        FavoriteProduct.objects
        .filter(user=user)
        .select_related("product")
        .annotate(is_favorite=Value(True, output_field=BooleanField()))
    )

    context = {
        "title": "House Style - Favorite Products",
        "favorite_products": favorite_products,
    }

    return render(request, "goods/favorite_products.html", context)


@login_required
@csrf_exempt
def toggle_favorite_view(request):
    if request.method == "POST":
        product_id = request.POST.get("product_id")

        if not product_id or not product_id.isdigit():
            logger.error("Invalid product_id to choose favorite product")
            return JsonResponse({"error": "Invalid product_id"}, status=400)

        user = request.user

        try:
            favorite_product = FavoriteProduct.objects.get(user=user, product_id=product_id)
            favorite_product.delete()
            is_favorite = False
        except FavoriteProduct.DoesNotExist:
            logger.error("Favorite product not found")

            FavoriteProduct.objects.create(user=user, product_id=product_id)
            is_favorite = True

        favorites_count = user.favoriteproduct_set.count()

        return JsonResponse({"is_favorite": is_favorite, "favorites_count": favorites_count})
    else:
        logger.error("Method not allowed for toggle favorite")
        return JsonResponse({"error": "Method not allowed"}, status=405)


@login_required
@csrf_exempt
def add_rating_view(request, product_id):
    if request.method == "POST":
        user = request.user
        rating_value = int(request.POST.get("rating"))

        try:
            product = Product.objects.get(id=product_id)
            existing_rating = Rating.objects.filter(user=user, product=product).first()

            if existing_rating:
                existing_rating.rating = rating_value
                existing_rating.save()
            else:
                Rating.objects.create(user=user, product=product, rating=rating_value)

            product.refresh_from_db()
            average_rating = product.average_rating()

            return JsonResponse({"success": True, "average_rating": average_rating})
        except Product.DoesNotExist:
            logger.error("Product not found to evaluate it")
            return JsonResponse({"success": False, "error": "Product not found"}, status=404)
        except Exception as e:
            logger.exception(f"An unexpected error occurred: {str(e)}")
            return JsonResponse({"success": False, "error": str(e)}, status=500)
    else:

goods/templates/goods/category_create.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
          <h2 class="text-center mb-4">Create category...</h2>
          <form action="{% url 'catalog:create_category' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
              <label for="id_name" class="form-label">Name</label>
              <input type="text" class="form-control"
                     value="{% if form.name.value %}{{ form.name.value }}{% endif %}"
                     name="name" id="id_name"
                     placeholder="Enter category name..." required>
            </div>
            <button type="submit" class="btn btn-dark btn-block">Create category</button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}


{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}
  <!-- Content on page -->
  <div class="container mt-5">
    <div class="card mb-4 custom-shadow">
      <div class="row">
        <!-- Thumbnails -->
        <div class="col-md-4">
          {% if product.image_product %}
            <img src="{{ product.image_product.url }}"
                 class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1" alt="">
          {% else %}
            <img src="{% static 'deps/images/Not found image.png' %}"
                 class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1" alt="">
          {% endif %}
        </div>
        <div class="col-md-4 ">
          <p class="product_id mt-3">id: {{ product.display_id }}</p>

          <div class="star-container" data-product-id="{{ product.id }}" data-average-rating="{{ product.average_rating }}">
            <p>
              {% for i in "12345" %}
                {% if i|add:"0" <= product.average_rating %}
                  <span class="star star-filled" data-rating="{{ i|add:'0' }}">&#9733;</span>
                {% else %}
                  <span class="star star-empty" data-rating="{{ i|add:'0' }}">&#9733;</span>
                {% endif %}
              {% endfor %}
            </p>
          </div>

        </div>

        <div class="col-md-1"></div>
        <div class="col-md-3 mt-3">
          {% if user.is_staff %}
          <a href="{% url 'catalog:product_update' product.slug %}"
             class="btn btn-secondary link-to-page float-right mr-2">
            Update
          </a>&#8194;
          <a href="{% url 'catalog:product_delete' product.slug %}"
             class="btn btn-danger link-to-page float-right">
            Delete
          </a>
        {% endif %}
        </div>
        <!-- Zoom of picture in modal window -->
        <div class="modal fade" id="imageModal1" tabindex="-1"
             aria-labelledby="imageModal1Label" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
              </div>
              <div class="modal-body">
                {% if product.image_product %}
                  <img src="{{ product.image_product.url }}" class="img-fluid" alt="Image 1">
                {% else %}
                  <img src="{% static 'deps/images/Not found image.png' %}" class="img-fluid" alt="Image 1">
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Product description -->
      <div class="card-body">
         <div class="d-flex">
          <p class="card-text">Price: <strong>{{ product.sell_price }} $</strong></p>&#8195;&#8195;&#8195;&#8195;&#8195;&#8195;&#8195;

          {% if user.is_authenticated %}
            <div class="product-links heart mx-5">
              {% if product.id in favorite_products %}
                <a href="#" class="favorite-icon favorite add-to-favorites" data-product-id="{{ product.id }}">
                  <i class="bi bi-heart-fill"></i>
                </a>
              {% else %}
                <a href="#" class="favorite-icon add-to-favorites" data-product-id="{{ product.id }}">
                  <i class="bi bi-heart"></i>
                </a>
              {% endif %}
            </div>
          {% endif %}
         </div>

        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description }}</p>
        <a href="{% url "cart:cart_add" %}" class="btn btn-dark add-to-cart" data-product-id="{{ product.id }}">
          {% csrf_token %}
          Add to cart
        </a>
      </div>
    </div>
  </div>

  <div class="container mt-5">
  <div class="card mb-4 custom-shadow p-3">
  {% if user.is_authenticated %}
    <div class="row">
      <div class="single-form-left">
        <!-- contact form grid -->
        <div class="contact-single">
          <h2 class="editContent" style="outline: none; cursor: inherit;">
            <span class="sub-tittle editContent" style="outline: none; cursor: inherit;">
              <small>{{ product.product_review.count }}</small>
            </span>
            Leave a review
          </h2>

          <form action="{% url 'catalog:review-create' product.id %}" method="post" class="mt-4" id="formReview">
            {% csrf_token %}
            <input type="hidden" name="parent" id="contactparent" value="">
            <div class="form-group editContent">

              <label for="contactcomment" class="editContent">
                <strong>Your comment*</strong>
              </label>
              <textarea class="form-control border mt-3" rows="5"
                        id="contactcomment" required="" name="text">
              </textarea>
            </div>
            <div class="d-sm-flex">
              <div class="col-sm-6 form-group p-0 editContent" style="outline: none; cursor: inherit;">
                <label for="contactusername" class="editContent mt-3">
                  <strong>Name*</strong>
                </label>
                <input type="text" class="form-control border mt-2"
                       id="contactusername" required=""
                       name="username" value="{{ request.user.username }}"
                       readonly
                >
              </div>&#8194;
              <div class="col-sm-6 form-group ml-sm-3 editContent" style="outline: none; cursor: inherit;">
                <label for="contactemail" class="editContent mt-3">
                  <strong>Email*</strong>
                </label>
                <input type="email" class="form-control border mt-2"
                       id="contactemail" required=""
                       name="email" value="{{ request.user.email }}"
                       readonly
                >
              </div>
            </div>
            <br>
            <button type="submit" class="btn btn-secondary" style="outline: none; cursor: inherit; font-size: 20px">Submit</button>
          </form>

        </div>
        <!--  //contact form grid ends here -->
      </div>
    </div>


    <br>
    <hr>
  {% endif %}

    <br><br>
    <hr>
    <div>

      <h3 class="editContent" style="outline: none; cursor: inherit;">
        <span class="sub-tittle editContent" style="outline: none; cursor: inherit;"></span>
        Comments
      </h3>
      <hr>
      {% for review in product.get_review %}
        <div class="media py-5">

          <img src="{{ review.user.image_user.url }}" class="mr-3 img-fluid" alt="image" width="60">&#8195;&#8195;&#8195;
          <div class="media-body mt-4">
            <h5 class="mt-0 editContent">{{ review.user.first_name }}</h5>
            <p class="mt-2 editContent" style="outline: none; cursor: inherit;">{{ review.text }}</p>

            {% if user.is_authenticated %}
              {% if user.is_staff %}
                {% if review.user != request.user %}
                <a href="#formReview"
                   onclick="addReview('{{ review.user.first_name }}','{{ review.id }}')">
                  Answer
                </a>
                {% endif %}
              {% endif %}
            {% endif %}

            {% for rew in review.review_set.all %}
              <div class="media mt-5 editContent">
                <div class="row">
                  <div class="col-md-2"></div>
                  <div class="col-md-10">
                    <a class="pr-3" href="#">
                      <img src="{{ rew.user.image_user.url }}" class="img-fluid" alt="image" width="60">
                    </a>
                    <div class="media-body">
                      <h5 class="mt-0 editContent">{{ rew.user.first_name }}</h5>
                      <p class="mt-2 editContent">{{ rew.text }}</p>
                    </div>
                  </div>
                </div>
              </div>

            {% endfor %}

          </div>

        </div><hr>
      {% endfor %}
    </div>
  </div>
  </div>

  <script>
    function addReview(first_name, id) {
      document.getElementById("contactparent").value = id;
      document.getElementById("contactcomment").innerText = `${first_name}, `
    }
  </script>

  <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
  <script src="{% static 'deps/js/jquery-catalog.js' %}"></script>
  <script src="{% static 'deps/js/jquery-rating.js' %}"></script>



{% endblock %}

goods/templates/goods/product_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
          <h2 class="text-center mb-4">Remove product...</h2>
          <hr>
          <p>
            Are you sure you want to delete the product: <strong>{{ product }}</strong>?
          </p>

          <form action="{% url 'catalog:product_delete' product.slug %}" method="post">
          {% csrf_token %}
          <hr>
          <br>

          <input type="submit" value="Yes, delete" class="btn btn-danger">
          <a href="{{ product.get_absolute_url }}" class="btn btn-secondary">Cancel</a>
        </form>


        </div>
      </div>
    </div>
  </div>

{% endblock %}

goods/templates/goods/product_create.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
          <h2 class="text-center mb-4">Create product...</h2>
          <form action="{% url 'catalog:create_product' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}

            <div class="mb-3">
              <label for="id_name" class="form-label">Name*</label>
              {{ form.name }}
            </div>

            <div class="mb-3">
              <label for="id_description" class="form-label">Description*</label>
              {{ form.description }}
            </div>

            <div class="mb-3">
              <label for="id_price" class="form-label">Price*</label>
              {{ form.price }}
            </div>

            <div class="mb-3">
              <label for="id_discount" class="form-label">Discount</label>
              {{ form.discount }}
            </div>

            <div class="mb-3">
              <label for="id_quantity" class="form-label">Quantity</label>
              {{ form.quantity }}
            </div>

            <div class="mb-3">
                <label for="id_category" class="form-label">Category*</label>
                {{ form.category }}
            </div>

            <div class="mb-3">
              <label for="id_image_product" class="form-label">Image</label>
              <div class="form-control">
                {{ form.image_product }}
              </div>
            </div>

            <button type="submit" class="btn btn-dark btn-block">Create product</button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

goods/templates/goods/product_update.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
          <h2 class="text-center mb-4">Edit product...</h2>
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}

            <div class="mb-3">
              <label for="id_name" class="form-label">Name*</label>
              {{ form.name }}
            </div>

            <div class="mb-3">
              <label for="id_description" class="form-label">Description*</label>
              {{ form.description }}
            </div>

            <div class="mb-3">
              <label for="id_price" class="form-label">Price*</label>
              {{ form.price }}
            </div>

            <div class="mb-3">
              <label for="id_discount" class="form-label">Discount</label>
              {{ form.discount }}
            </div>

            <div class="mb-3">
              <label for="id_quantity" class="form-label">Quantity</label>
              {{ form.quantity }}
            </div>

            <div class="mb-3">
                <label for="id_category" class="form-label">Category*</label>
                {{ form.category }}
            </div>

            <div class="mb-3">
              <label for="id_image_product" class="form-label">Image</label>
              <div class="form-control">
                {{ form.image_product }}
              </div>
            </div>

            <button type="submit" class="btn btn-dark btn-block">Edit product</button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}