goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"

urlpatterns = [
    path("search/", views.catalog_view, name="search"),
    path("favorite-products/", views.favorite_products_view, name="favorite_products"),
    path("toggle-favorite/", views.toggle_favorite_view, name="toggle_favorite"),
    path("add-rating/<int:product_id>/", views.add_rating_view, name="add_rating"),
    path("create-category/", views.category_create_view, name="create_category"),
    path("create-product/", views.product_create_view, name="create_product"),
    path("<slug:category_slug>/", views.catalog_view, name="index"),
    path("product/<slug:product_slug>/", views.product_view, name="product"),
    path("product/<slug:product_slug>/edit/", views.product_update_view, name="product_update"),
    path("product/<slug:product_slug>/remove/", views.product_delete_view, name="product_delete"),
    path("review/<int:product_id>/", views.create_review, name="review-create"),
]

main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path("create-order/", views.create_order_view, name="create_order"),
    path(
        "<int:pk>/create-checkout-session/",
        views.create_checkout_session,
        name="create-checkout-session"
    ),
    path("success/", views.success_view, name="success"),
    path("cancel/", views.cancel_view, name="cancel"),
]

store_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("subscribe/", include("subscribe.urls", namespace="subscribe")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "store_service.views.custom_404"
handler500 = "store_service.views.custom_500"

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("profile/", views.profile_view, name="profile"),
    path("users-cart/", views.users_cart_view, name="users_cart"),
    path("logout/", views.logout_view, name="logout"),
    path("<int:pk>/password/", views.change_password_view, name="password-change"),
    path("password-success/", views.password_success_view, name="password-success"),
    path(
        "reset_password/", views.reset_password_view, name="reset_password"
    ),
    path(
        "reset_password_sent/", views.reset_password_done_view, name="password_reset_done"
    ),
    path(
        "reset/<uidb64>/<token>/", views.reset_password_confirm_view, name="password_reset_confirm"
    ),
    path(
        "reset_password_complete/", views.reset_password_complete_view, name="password_reset_complete"
    ),
]

users/models.py
import logging
import os
import uuid

from PIL import Image
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext as _
from phonenumber_field.modelfields import PhoneNumberField

logger = logging.getLogger(__name__)


def user_image_file_path(instance, filename):
    _, extension = os.path.splitext(filename)
    filename = f"{slugify(instance.username)}-{uuid.uuid4()}{extension}"

    return os.path.join("uploads/user_pics/", filename)


class UserManager(BaseUserManager):
    """Define a model manager for User model."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            logger.error("The given email must be set")
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            logger.error("Superuser must have is_staff=True.")
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            logger.error("Superuser must have is_superuser=True.")
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    image_user = models.ImageField(upload_to=user_image_file_path, blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return self.username

    def save(
        self,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None
    ):
        super().save()

        if self.image_user:
            img = Image.open(self.image_user.path)

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image_user.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ("username", "password")


class UserProfileForm(UserChangeForm):
    image_user = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            "image_user",
            "first_name",
            "last_name",
            "username",
            "email",
        )

users/views.py
import logging

from django.contrib import auth, messages
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.tokens import default_token_generator

from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.http import urlsafe_base64_decode

from carts.models import Cart
from orders.models import Order, OrderItem
from users.forms import UserLoginForm, UserProfileForm, UserRegisterForm

logger = logging.getLogger(__name__)


def login_view(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            email = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=email, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get("next", None)
                if redirect_page and redirect_page != reverse("user:logout"):
                    return HttpResponseRedirect(request.POST.get("next"))

                logger.info(f"Welcome {user.username} to our site")
                messages.success(request, f"Welcome {user.username} to our site")
                return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserLoginForm()

    context = {
        "title": "House Style - Authorization",
        "form": form
    }

    return render(request=request, template_name="users/login.html", context=context)


def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            logger.info(f"{user.username}, You have successfully registered and logged in")
            messages.success(request, f"{user.username}, You have successfully registered and logged in")
            return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserRegisterForm()

    context = {
        "title": "House Style - Registration",
        "form": form
    }
    return render(request=request, template_name="users/register.html", context=context)


@login_required
def profile_view(request):
    if request.method == "POST":
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()

            logger.info("Profile successfully updated")
            messages.success(request, "Profile successfully updated")
            return HttpResponseRedirect(reverse("user:profile"))
    else:
        form = UserProfileForm(instance=request.user)

    orders = Order.objects.filter(user=request.user).prefetch_related(
        Prefetch(
            "order_items",
            queryset=OrderItem.objects.select_related("product"),
        )
    ).order_by("-id")

    context = {
        "title": "House Style - Personal Account",
        "form": form,
        "orders": orders,
    }
    return render(request=request, template_name="users/profile.html", context=context)


def users_cart_view(request):
    context = {
        "title": "House Style - User Cart",
    }
    return render(request=request, template_name="users/users_cart.html", context=context)


@login_required
def logout_view(request):
    logger.info(f"{request.user.username}, You left your account")
    messages.success(request, f"{request.user.username}, You left your account")
    auth.logout(request)
    return redirect(reverse("main:index"))


@login_required
def change_password_view(request, pk):
    user = request.user

    if request.method == "POST":
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)

            logger.info("Password changed successfully.")
            messages.success(request, "Password changed successfully.")

            return redirect(reverse("user:password-success"))
    else:
        form = PasswordChangeForm(user)

    context = {
        "title": "House Style - Change Password",
        "form": form,
        "user": user
    }

    return render(request=request, template_name="users/password_change_form.html", context=context)


@login_required
def password_success_view(request):

    context = {
        "title": "House Style - Changed Password",
    }
    return render(
        request=request, template_name="users/password_change_done.html", context=context
    )


def reset_password_view(request):
    form = PasswordResetForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save(
                request=request,
                email_template_name="users/password_reset_email.html",
            )

            logger.info("Message sent successfully.")
            messages.success(request, "Message sent successfully.")
            return redirect(reverse("user:password_reset_done"))

    context = {
        "title": "House Style - Reset Password",
        "form": form,
    }

    return render(
        request=request, template_name="users/password_reset_form.html", context=context
    )


def reset_password_done_view(request):
    context = {
        "title": "House Style - Reset Password Done"
    }

    return render(
        request=request, template_name="users/password_reset_done.html", context=context
    )


def reset_password_confirm_view(request, uidb64, token):
    user_id = urlsafe_base64_decode(uidb64).decode("utf-8")
    user = get_user_model().objects.get(pk=user_id)

    if default_token_generator.check_token(user, token):
        validlink = True

        if request.method == "POST":
            form = SetPasswordForm(data=request.POST, user=user)
            if form.is_valid():
                form.save()

                logger.info("Password reset successfully.")
                messages.success(request, "Password reset successfully.")
                return redirect(reverse("user:password_reset_complete"))
        else:
            form = SetPasswordForm(user=user)
    else:
        validlink = False
        form = None

    context = {
        "title": "House Style - Password Confirm",
        "validlink": validlink,
        "form": form,
        "uid": uidb64,
        "token": token,
    }

    return render(
        request=request, template_name="users/password_reset_confirm.html", context=context
    )


def reset_password_complete_view(request):
    context = {
        "title": "House Style - Password Complete"
    }

    return render(
        request=request, template_name="users/password_reset_complete.html", context=context
    )

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
          <h2 class="text-center mb-4">Login</h2>
          <form action="{% url 'user:login' %}" method="post">
            {% csrf_token %}
            {% if request.GET.next %}
              <input type="hidden" name="next" value={{request.GET.next}}>
            {% endif %}
            <div class="mb-3">
              <label for="id_email" class="form-label">Email</label>
              <input type="email" class="form-control"
                     value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                     name="username" id="id_email"
                     placeholder="Enter your email..." required>
            </div>
            <div class="mb-3">
              <label for="id_password" class="form-label">Password</label>
              <input type="password" class="form-control" name="password" id="id_password"
                     placeholder="Enter your password..." required>
            </div>
            <button type="submit" class="btn btn-dark btn-block">Sign in</button>
          </form>
          <div class="mt-3">
            <a href="{% url 'user:reset_password' %}">Forgot password?</a> | Don't have an account? <a href="{% url 'user:register' %}">Create account</a>
          </div>
          <hr>
          <div class="text-center">
            <p>Or log in with:</p>
            <a href="#" class="btn btn-dark">
              <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Catalog Icon" width="16" height="16">
              Google
            </a>
            <a href="#" class="btn btn-dark">
              <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16" height="16">
              Facebook
            </a>
            <a href="#" class="btn btn-dark">
              <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16" height="16">
              GitHub
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
          <h1>Password reset complete</h1>
          <p>
            Your new password has been set. You can log in now on the <a href="{% url 'user:login' %}">log in page</a>.
          </p>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
          <h1 class="text-center mb-4">Forgotten your password?</h1>
          <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

          <form action="{% url 'user:reset_password' %}" method="post">
            {% csrf_token %}

            <div class="row">
              <div class="col-md-12 mb-3">
                <label for="id_email" class="form-label">Email*</label>
                <input type="email" class="form-control" id="id_email"
                       value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                       name="email"
                       placeholder="Enter your email..." required>
                       {% if form.email.errors %}
                         <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                       {% endif %}
              </div>
            </div>
            <button type="submit" class="btn btn-dark btn-block">Send me instructions!</button>
          </form>
                  </div>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block title %}{{ title }}{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row">
        <!-- Profile with user data -->
        <div class="col-md-5">
          <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
            <h3 class="text-center mb-4">User Profile</h3>
            <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-12 mb-3 text-center">

                  <img src="{% if user.image_user %}{{ user.image_user.url }}
                       {% else %}{% static 'deps/images/baseavatar.jpg' %}{% endif %}"
                       alt="User image" class="img-fluid rounded-circle" style="max-width: 150px;">

                  <input type="file" class="form-control mt-3" id="id_image_user"
                         name="image_user"
                         accept="image_user/*">
                         {% if form.image_user.errors %}
                           <div class="alert alert-danger alert-dismissible fade show">{{form.image_user.errors}}</div>
                         {% endif %}
                </div>
                <div class="col-md-12 mb-3">
                  <label for="id_first_name" class="form-label">First Name*</label>
                  <input type="text" class="form-control" id="id_first_name" name="first_name"
                         placeholder="Enter your first name..." value="{{ user.first_name }}" required>
                          {% if form.first_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                          {% endif %}
                </div>
                <div class="col-md-12 mb-3">
                  <label for="id_last_name" class="form-label">Last Name*</label>
                  <input type="text" class="form-control" id="id_last_name" name="last_name"
                         placeholder="Enter your last name..." value="{{ user.last_name }}" required>
                         {% if form.last_name.errors %}
                           <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                         {% endif %}
                </div>
                <div class="col-md-12 mb-3">
                  <label for="id_username" class="form-label">Username*</label>
                  <input type="text" class="form-control" id="id_username" name="username"
                         placeholder="Enter your username..." value="{{ user.username }}" required>
                         {% if form.username.errors %}
                           <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                         {% endif %}
                </div>
                <div class="col-md-12 mb-3">
                  <label for="id_email" class="form-label">Email*</label>
                  <input type="email" class="form-control" id="id_email" name="email"
                         placeholder="Enter your email *youremail@example.com" value="{{ user.email }}" required>
                         {% if form.email.errors %}
                           <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                         {% endif %}
                </div>
              </div>
              <button type="submit" class="btn btn-dark">Save</button>
            </form>
            You want to change your password? <a href="{% url 'user:password-change' user.id %}">Here's the form</a>
          </div>
        </div>

        {% user_carts request as carts %}
        <!-- Cart -->
        <div class="col-md-7">
          <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
            <h3 class="text-center mb-4">Cart</h3>
            <div class="container" id="cart-items-container">
              <!-- Cart marking -->
              {% include "carts/includes/included_cart.html" %}
              <!-- End cart marking -->
            </div>
          </div>
        </div>

        <!-- Placed orders -->
        <div class="col-md-12">
          <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
            <h3 class="text-center mb-4">My orders</h3>
            <!-- Orders marking -->
            <div class="container">
              <div class="accordion" id="accordionExample">
              {% for order in orders %}
                <div class="accordion-item">
                  <h2 class="accordion-header" id="heading{{ order.id }}">
                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                      Order № {{ order.id }} - {{ order.created_at }}
                      | Require the delivery: <strong class="mx-2">{{order.requires_delivery}}</strong>
                      | Order status: <strong class="mx-2">{{ order.status_order }}</strong>
                      | Payment status: <strong class="mx-2">{{ order.is_paid }}</strong>
                    </button>
                  </h2>
                  <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <table class="table table-dark table-hover">
                        <thead>
                        <tr>
                          <th>Product</th>
                          <th>Quantity</th>
                          <th>Price</th>
                          <th>Total price</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in order.order_items.all %}
                        <tr>
                          <td><a class="text-white" href="{% url 'goods:product' item.product.slug %}">{{ item.product.name }}</a></td>
                          <td>{{ item.quantity }}</td>
                          <td>{{ item.price }} $</td>
                          <td>{{ item.products_price }} $</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                       <div class="d-flex justify-content-between">
                         <p><strong>Total:</strong></p>
                         <p><strong>{{ order.order_items.total_price }} $</strong></p>
                       </div>
                       {% if order.payment_on_get %}
                         {% if not order.is_paid %}
                           <div>
                             <a href="{% url 'orders:create-checkout-session' order.id %}" class="btn btn-secondary">Payment</a>
                           </div>
                         {% endif %}
                       {% endif %}
                    </div>
                  </div>
                </div>
              {% endfor %}

              </div>
            </div>

            <!-- End orders marking -->
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block modal_cart %}
  {% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}

  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
          <h2 class="text-center mb-4">Register</h2>
          <form action="{% url 'user:register' %}" method="post">
            {% csrf_token %}
            <div class="row">

              <div class="col-md-6 mb-3">
                <label for="id_first_name" class="form-label">First Name*</label>
                <input type="text" class="form-control" id="id_first_name"
                       value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                       name="first_name"
                       placeholder="Enter your first name..." required>
                       {% if form.first_name.errors %}
                         <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                       {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_last_name" class="form-label">Last Name*</label>
                <input type="text" class="form-control" id="id_last_name"
                       value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                       name="last_name"
                       placeholder="Enter your last name..." required>
                       {% if form.last_name.errors %}
                         <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                       {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_username" class="form-label">Username*</label>
                <input type="text" class="form-control" id="id_username"
                       value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                       name="username"
                       placeholder="Enter your username..." required>
                       {% if form.username.errors %}
                         <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                       {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_email" class="form-label">Email*</label>
                <input type="email" class="form-control" id="id_email"
                       value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                       name="email"
                       placeholder="Enter your email..." required>
                       {% if form.email.errors %}
                         <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                       {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_password1" class="form-label">Password*</label>
                <input type="password" class="form-control" id="id_password1"
                       value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                       name="password1"
                       placeholder="Enter your password..." required>
                       {% if form.password1.errors %}
                         <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                       {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_password2" class="form-label">Confirm Password*</label>
                <input type="password" class="form-control" id="id_password2"
                       value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                       name="password2"
                       placeholder="Confirm your password..." required>
                       {% if form.password2.errors %}
                         <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                       {% endif %}
              </div>

            </div>
            <button type="submit"
                    class="btn btn-dark btn-block">Sign up</button>
          </form>
          <div class="mt-3">
            Already have an account? <a href="{% url 'user:login' %}">Sign in</a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}